server:
  port: 8081



spring:
  data:
    neo4j:
          username: neo4j
          password: 65125109
          uri: http://localhost:7474
  redis:
    database: 0
    host: localhost
    password: 123456
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 10
        max-wait: -1
  datasource:
    url: jdbc:mysql://localhost:3306/ebook
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  kafka: 
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ebook
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer   
        
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
      